require('tm')
require('SnowballC')
myCorpus<-Corpus(VectorSource(articles$content))
myCorpus = tm_map(myCorpus, PlainTextDocument)
myCorpus <- tm_map(myCorpus, content_transformer(tolower))
myCorpus = tm_map(myCorpus, removePunctuation)
myCorpus = tm_map(myCorpus, removeWords, c(stopwords("english"),stopwords("SMART")))
myCorpus = tm_map(myCorpus, stemDocument,lazy=TRUE)

dtm = DocumentTermMatrix(myCorpus) 
notSparse = removeSparseTerms(dtm, 0.99)
a = as.matrix(notSparse)
frequency = colSums(a)
frequency <- sort(frequency, decreasing=TRUE)
head(frequency)